spring:
  application:
    name: ScheduleService

  datasource:
    url: jdbc:mysql://localhost:3306/ScheduleService
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 3636
  servlet:
    context-path: /schedule
